### ISSUE TITLE
Word embedding augmentation not registered

### ISSUE THREAD

**Issue by martincjespersen** [KennethEnevoldsen/augmenty#36]
## How to reproduce the behaviour
```python
import spacy
import augmenty
nlp = spacy.load('en_core_web_lg')
danish_wordemb = augmenty.load("word_embedding.v1", nlp=nlp)
```

**Error message:**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python3.9/site-packages/augmenty/util.py", line 114, in load
    aug = spacy.registry.augmenters.get(augmenter)
  File "/python3.9/site-packages/catalogue/__init__.py", line 96, in get
    raise RegistryError(err.format(name, current_namespace, available))
catalogue.RegistryError: Cant't find 'word_embedding.v1' in registry spacy -> augmenters. Available names: char_replace.v1, char_replace_random.v1, char_swap.v1, conditional_token_casing.v1, da_historical_noun_casing.v1, da_æøå_replace.v1, ents_format.v1, ents_replace.v1, grundtvigian_spacing_augmenter.v1, keystroke_error.v1, per_replace.v1, random_casing.v1, random_starting_case.v1, remove_spacing.v1, spacing_insertion.v1, spacy.lower_case.v1, spacy.orth_variants.v1, spongebob.v1, token_replace.v1, token_swap.v1, upper_case.v1, wordnet_synonym.v1
```

## Your Environment
* augmenty Version Used: 0.0.7
* Operating System: Mac OS / Windows
* Python Version Used:  3.6.5 & 3.9.5
* spaCy Version Used: spacy==3.1.1
* NLTK Version Used: nltk==3.6.2
* Environment Information: conda environment

**Comment by KennethEnevoldsen** [comment]
This is fixed in the latest PR.
